---
- name: Connecting  Webserver
  hosts: webserver01
  remote_user: ec2-user
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false
  collections:
    - servicenow.itsm

  vars:
    SN_USERNAME: admin
    SN_PASSWORD: 
    SN_INSTANCE: 

  tasks:

    - name: Create incident
      servicenow.itsm.incident:
       instance:
         host: https://{{ SN_INSTANCE }}.service-now.com/
         username: "{{ SN_USERNAME }}"
         password: "{{ SN_PASSWORD }}"
       state: new
       caller: admin
       short_description: Http Server stopped running
       description: Http service is inactive, EDA will attempt to correct. on Server XXXXX

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true
