---
- name: Connecting Webserver
  hosts: webserver01
  remote_user: ec2-user
  gather_facts: false
#  vars:

  tasks:

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true

    - name: Firewall is Enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: HTTP Service is Open on Firewall
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: yes     
